# Generated by Django 3.2.3 on 2021-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('eamil', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
