# Generated by Django 3.2.3 on 2021-05-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='eamil',
            new_name='email',
        ),
    ]
